"use client";

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, Terminal, Zap, Shield, Search, ChevronRight, Menu, X, Check, Copy, Code, Cpu, Lock, FileText, Server } from 'lucide-react';
import { Logo } from '@/components/ui/Logo';

interface DocArticle {
  title: string;
  category: string;
  summary: string;
  codeSnippet?: {
    language: string;
    filename: string;
    code: string;
  };
  sections: {
    heading: string;
    content: string;
  }[];
}

const docsData: Record<string, DocArticle> = {
  // GETTING STARTED
  'Quick Start': {
    title: 'Quick Start Guide',
    category: 'Getting Started',
    summary: 'Set up your developer environment, initialize the ZPAY SDK, and broadcast your first autonomous transaction on the Stellar network in under 5 minutes.',
    codeSnippet: {
      language: 'typescript',
      filename: 'quickstart.ts',
      code: `import { ZPay } from '@zpay/sdk';

const client = new ZPay({
  apiKey: process.env.ZPAY_SECRET_KEY,
  network: 'mainnet'
});

// Broadcast instant payment
const payment = await client.payments.create({
  to: 'alice@zpay',
  amount: 25.50,
  currency: 'USDC',
  agentMemo: 'API compute micro-settlement'
});

console.log(\`Payment settled! Hash: \${payment.hash}\`);`
    },
    sections: [
      {
        heading: '1. Prerequisites',
        content: 'You need Node.js 18+ or Python 3.10+ installed. Obtain your API Key from the ZPAY developer dashboard under Settings > API Keys.'
      },
      {
        heading: '2. SDK Installation',
        content: 'Install the official ZPAY client library via npm (npm install @zpay/sdk) or pip (pip install zpay-python).'
      },
      {
        heading: '3. Verification',
        content: 'All payments instantly resolve to 64-character Stellar ledger sequence hashes with under 3-second settlement finality.'
      }
    ]
  },

  'Authentication': {
    title: 'Authentication & Signing',
    category: 'Getting Started',
    summary: 'Learn how ZPAY authenticates API requests and cryptographically signs on-chain transactions using ED25519 keypairs.',
    codeSnippet: {
      language: 'bash',
      filename: 'cURL',
      code: `curl -X POST https://api.zpay.route/v1/payments \\
  -H "Authorization: Bearer sk_live_99f01ab8c341" \\
  -H "Content-Type: application/json" \\
  -d '{"to":"bob@zpay", "amount":10.0, "currency":"USDC"}'`
    },
    sections: [
      {
        heading: 'API Keys',
        content: 'ZPAY uses prefixed secret keys: sk_live_ for mainnet execution and sk_test_ for sandbox testing on Stellar Testnet.'
      },
      {
        heading: 'ED25519 Request Signing',
        content: 'For automated agent spending, request headers must include X-ZPAY-Signature, generated by signing the HTTP body with your agent keypair.'
      }
    ]
  },

  'Your First Payment': {
    title: 'Executing Your First Payment',
    category: 'Getting Started',
    summary: 'A step-by-step walkthrough for sending cross-currency payments with automatic Stellar path routing.',
    codeSnippet: {
      language: 'typescript',
      filename: 'payment_example.ts',
      code: `const res = await client.payments.create({
  to: 'vendor@zpay',
  amount: 100,
  currency: 'USDC',
  slippageTolerance: 0.005, // 0.5% max slippage
  pathPayment: true // Auto-route from XLM liquidity pools
});`
    },
    sections: [
      {
        heading: 'Path Payment Engine',
        content: 'If your wallet holds XLM but the destination requires USDC, ZPAY automatically routes the transaction through Stellar DEX orderbooks at zero extra spread.'
      }
    ]
  },

  'ZPAY ID Guide': {
    title: 'ZPAY Universal Identifier (ID)',
    category: 'Getting Started',
    summary: 'Map complex 56-character public keys (e.g. GABX...77P) into clean, human-readable ZPAY handles like handle@zpay.',
    codeSnippet: {
      language: 'typescript',
      filename: 'resolve_id.ts',
      code: `const handleInfo = await client.id.resolve('alice@zpay');
console.log(handleInfo);
// { publicAddress: "GABX3...77P", upiVpa: "alice@okaxis", status: "active" }`
    },
    sections: [
      {
        heading: 'Federation Resolution Protocol',
        content: 'ZPAY IDs comply with Stellar SEP-0002 federation standards, resolving handles across both web3 wallets and Indian UPI VPA endpoints.'
      }
    ]
  },

  // API REFERENCE
  'API Overview': {
    title: 'REST API Overview',
    category: 'API Reference',
    summary: 'The ZPAY REST API provides low-latency endpoints for programmatic payment execution, wallet telemetry, and transaction streaming.',
    codeSnippet: {
      language: 'json',
      filename: 'Response Format',
      code: `{\n  "object": "payment",\n  "id": "pay_90218412",\n  "status": "succeeded",\n  "amount": "15.00",\n  "currency": "USDC",\n  "fee_sponsored": true,\n  "ledger_sequence": 51204912,\n  "created_at": "2026-07-31T23:20:00Z"\n}`
    },
    sections: [
      {
        heading: 'Base Endpoint',
        content: 'All production API calls should be made to https://api.zpay.route/v1 with application/json request payloads.'
      }
    ]
  },

  'Payments API': {
    title: 'Payments Endpoint Reference',
    category: 'API Reference',
    summary: 'Complete endpoint definitions for creating, retrieving, and listing transactions.',
    codeSnippet: {
      language: 'bash',
      filename: 'HTTP Request',
      code: `GET /v1/payments?limit=10&status=succeeded HTTP/1.1\nHost: api.zpay.route\nAuthorization: Bearer sk_live_99f01ab8c341`
    },
    sections: [
      {
        heading: 'POST /v1/payments',
        content: 'Parameters: to (string, required), amount (number, required), currency (string, required), agent_memo (string, optional).'
      },
      {
        heading: 'GET /v1/payments/:id',
        content: 'Retrieves verified on-chain details and proof-of-payment receipts for a specific payment ID.'
      }
    ]
  },

  'Webhooks': {
    title: 'Webhooks & Events',
    category: 'API Reference',
    summary: 'Listen for real-time payment settlements, escrow fulfillments, and failed path routing events in your backend.',
    codeSnippet: {
      language: 'typescript',
      filename: 'webhook_handler.ts',
      code: `import { verifySignature } from '@zpay/sdk';

app.post('/webhook', (req, res) => {
  const isVerified = verifySignature({
    payload: req.body,
    signature: req.headers['x-zpay-signature'],
    secret: process.env.ZPAY_WEBHOOK_SECRET
  });
  if (isVerified) {
    // Process payment.succeeded event
    res.status(200).send('OK');
  }
});`
    },
    sections: [
      {
        heading: 'Supported Event Types',
        content: 'payment.succeeded, payment.failed, escrow.created, escrow.released, upi.bridge_settled.'
      }
    ]
  },

  'Rate Limits': {
    title: 'Rate Limiting & Throttling',
    category: 'API Reference',
    summary: 'Understand API request quotas, burst thresholds, and automated retry backoff headers.',
    codeSnippet: {
      language: 'json',
      filename: 'HTTP Headers',
      code: `X-RateLimit-Limit: 1000\nX-RateLimit-Remaining: 998\nX-RateLimit-Reset: 1785516000`
    },
    sections: [
      {
        heading: 'Quota Limits',
        content: 'Free/Early Access: 100 requests/minute. Professional Tier: 5,000 requests/minute. Enterprise: Custom unthrottled node allocation.'
      }
    ]
  },

  // AI AGENT SDK
  'Agent SDK Intro': {
    title: 'AI Agent SDK Introduction',
    category: 'AI Agent SDK',
    summary: 'Equip your Autonomous AI Agents (LangChain, AutoGen, CrewAI) with self-custodial wallets and automatic micro-payment capabilities.',
    codeSnippet: {
      language: 'python',
      filename: 'agent_wallet.py',
      code: `from zpay import AgentWallet

wallet = AgentWallet.from_secret_key(os.getenv("AGENT_KEY"))

# Agent pays per API call autonomously
receipt = wallet.pay_x402(
    url="https://api.valuable-data.com/query",
    max_fee_usdc=0.001
)
print(f"Data unlocked! Receipt: {receipt.tx_hash}")`
    },
    sections: [
      {
        heading: 'Machine-to-Machine Commerce',
        content: 'The SDK provides wrapper functions that intercept HTTP 402 responses and automatically attach valid Stellar payment tokens.'
      }
    ]
  },

  'Deploying Agents': {
    title: 'Deploying Autonomous Agents',
    category: 'AI Agent SDK',
    summary: 'Best practices for running 24/7 background worker agents with automated transaction retry loops.',
    codeSnippet: {
      language: 'typescript',
      filename: 'agent_worker.ts',
      code: `import { ZPayAgentWorker } from '@zpay/sdk';

const agent = new ZPayAgentWorker({
  spendingCapDaily: 50.00, // $50 USDC daily limit
  autoApproveWhitelist: ['server@zpay', 'openai@zpay']
});

agent.startListening();`
    },
    sections: [
      {
        heading: 'Process Supervision',
        content: 'Run agent loops under PM2, Docker, or Kubernetes. The SDK maintains websocket reconnects to Stellar Horizon nodes.'
      }
    ]
  },

  'Agent Permissions': {
    title: 'Agent Spending Permissions & Caps',
    category: 'AI Agent SDK',
    summary: 'Enforce strict cryptographic guardrails so your AI agents can never overspend or drain wallet reserves.',
    codeSnippet: {
      language: 'typescript',
      filename: 'policy.ts',
      code: `const policy = {
  maxTransactionUsdc: 5.00,
  dailyBudgetUsdc: 100.00,
  allowedCurrencies: ['USDC', 'XLM'],
  requireApprovalIfOver: 20.00
};
client.agent.setPolicy(policy);`
    },
    sections: [
      {
        heading: 'On-Chain Guardrails',
        content: 'Policies are enforced locally in SDK memory and validated on-chain via multi-sig account pre-authorizations.'
      }
    ]
  },

  'Receipts': {
    title: 'Cryptographic Payment Receipts',
    category: 'AI Agent SDK',
    summary: 'Generate and verify zero-knowledge proof of payment receipts for automated multi-agent audit compliance.',
    codeSnippet: {
      language: 'json',
      filename: 'receipt.json',
      code: `{\n  "protocol": "x402",\n  "tx_hash": "a910bf23c847...",\n  "sender": "agent_alpha@zpay",\n  "recipient": "data_provider@zpay",\n  "proof": "ed25519_sig_990141..."\n}`
    },
    sections: [
      {
        heading: 'Auditability',
        content: 'Receipts can be submitted directly to enterprise accounting pipelines for instant tax deduction logging.'
      }
    ]
  },

  // SECURITY & AUTH
  'Security Model': {
    title: 'Security Architecture & Key Isolation',
    category: 'Security & Auth',
    summary: 'A detailed breakdown of ZPAY zero-trust key isolation, non-custodial storage, and threat mitigation.',
    codeSnippet: {
      language: 'text',
      filename: 'Architecture',
      code: `[Client SDK] ---> Encrypted Payload ---> [Stellar Horizon Node]
     |                                                  |
     +--- (Private Key stays on local HSM/Device) ------+`
    },
    sections: [
      {
        heading: 'Zero-Custody Principle',
        content: 'ZPAY servers never store, log, or transmit private keys. Key material is stored inside OS Keychain or Hardware Security Modules.'
      }
    ]
  },

  'Key Management': {
    title: 'Key Management & Hardware Wallets',
    category: 'Security & Auth',
    summary: 'How to integrate Ledger hardware wallets and AWS KMS for enterprise agent signing keys.',
    codeSnippet: {
      language: 'typescript',
      filename: 'kms_signer.ts',
      code: `import { KmsSigner } from '@zpay/kms';

const signer = new KmsSigner({
  keyId: 'arn:aws:kms:us-east-1:123456789:key/zpay-agent-key'
});
const client = new ZPay({ signer });`
    },
    sections: [
      {
        heading: 'Enterprise Key Vaults',
        content: 'Avoid raw environment variables in production by delegating transaction signing to AWS KMS or GCP Cloud HSM.'
      }
    ]
  },

  'Audit Logs': {
    title: 'Immutable On-Chain Audit Logs',
    category: 'Security & Auth',
    summary: 'Query historic ledger sequences and verify state transitions.',
    codeSnippet: {
      language: 'typescript',
      filename: 'audit.ts',
      code: `const logs = await client.audit.getLogs({
  fromLedger: 51200000,
  toLedger: 51204912
});
console.log(\`Verified \${logs.length} on-chain state changes.\`);`
    },
    sections: [
      {
        heading: 'Tamper-Proof Audit Trails',
        content: 'Every payment, memo, and contract execution is cryptographically linked to the Stellar consensus ledger.'
      }
    ]
  },

  'Compliance': {
    title: 'Compliance, SEP-12 & Sanctions',
    category: 'Security & Auth',
    summary: 'Automated AML screening and Stellar SEP-12 KYC compliance integration for fiat bridge off-ramps.',
    codeSnippet: {
      language: 'json',
      filename: 'Compliance Status',
      code: `{\n  "sanctions_screen": "PASSED",\n  "ofac_status": "CLEARED",\n  "sep12_kyc_level": "LEVEL_2_VERIFIED"\n}`
    },
    sections: [
      {
        heading: 'Regulatory Alignment',
        content: 'ZPAY fiat bridge endpoints automatically check OFAC sanctions databases before authorizing crypto-to-fiat conversions.'
      }
    ]
  }
};

const sidebarLinks = [
  {
    category: 'Getting Started',
    icon: Zap,
    items: ['Quick Start', 'Authentication', 'Your First Payment', 'ZPAY ID Guide'],
  },
  {
    category: 'API Reference',
    icon: Terminal,
    items: ['API Overview', 'Payments API', 'Webhooks', 'Rate Limits'],
  },
  {
    category: 'AI Agent SDK',
    icon: BookOpen,
    items: ['Agent SDK Intro', 'Deploying Agents', 'Agent Permissions', 'Receipts'],
  },
  {
    category: 'Security & Auth',
    icon: Shield,
    items: ['Security Model', 'Key Management', 'Audit Logs', 'Compliance'],
  },
];

export default function DocsPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState('Getting Started');
  const [activeItem, setActiveItem] = useState('Quick Start');
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);

  // Live real-time search filtering
  const filteredSections = useMemo(() => {
    if (!searchQuery.trim()) return sidebarLinks;
    const q = searchQuery.toLowerCase();
    
    return sidebarLinks.map(section => ({
      ...section,
      items: section.items.filter(item => {
        const doc = docsData[item];
        return (
          item.toLowerCase().includes(q) ||
          section.category.toLowerCase().includes(q) ||
          (doc && doc.summary.toLowerCase().includes(q))
        );
      })
    })).filter(section => section.items.length > 0);
  }, [searchQuery]);

  const currentDoc = docsData[activeItem] || docsData['Quick Start'];

  const copyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-black text-white selection:bg-white/20 font-[family-name:var(--font-jakarta)] flex flex-col md:flex-row">
      
      {/* Mobile Header */}
      <div className="md:hidden flex items-center justify-between p-4 border-b border-white/10 bg-[#070707] sticky top-0 z-50">
        <div className="flex items-center gap-2">
          <Logo className="w-6 h-6" />
          <span className="font-bold text-sm tracking-tight text-white">ZPAY Docs</span>
        </div>
        <button 
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)} 
          className="p-2 text-white/80 rounded-lg border border-white/10 bg-white/5"
          aria-label="Toggle menu"
        >
          {mobileMenuOpen ? <X size={18} /> : <Menu size={18} />}
        </button>
      </div>

      {/* Sidebar */}
      <aside className={`
        fixed md:sticky top-[57px] md:top-0 h-[calc(100vh-57px)] md:h-screen w-full md:w-72 lg:w-80 bg-[#070707] border-r border-white/10 flex flex-col z-40 transition-transform duration-300 ease-in-out
        ${mobileMenuOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}
      `}>
        <div className="hidden md:flex items-center gap-3 p-6 border-b border-white/5">
          <Logo className="w-7 h-7" />
          <span className="font-bold text-lg tracking-tight">ZPAY Documentation</span>
        </div>

        <div className="p-4 sm:p-6 overflow-y-auto flex-1">
          {/* Functional Real-time Search Input */}
          <div className="relative mb-6">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/40 pointer-events-none" />
            <input 
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search documentation..."
              className="w-full pl-9 pr-8 py-2.5 rounded-xl border border-white/15 bg-white/5 text-sm text-white placeholder-white/40 focus:outline-none focus:border-gold/50 transition-colors"
            />
            {searchQuery && (
              <button 
                onClick={() => setSearchQuery('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40 hover:text-white"
              >
                <X size={14} />
              </button>
            )}
          </div>

          <div className="space-y-8">
            {filteredSections.length > 0 ? (
              filteredSections.map((section) => {
                const { icon: Icon } = section;
                return (
                  <div key={section.category}>
                    <h4 className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.15em] text-white/50 mb-3">
                      <Icon size={13} className="text-gold" />
                      {section.category}
                    </h4>
                    <ul className="space-y-1">
                      {section.items.map((item) => {
                        const isSelected = item === activeItem;
                        return (
                          <li key={item}>
                            <button 
                              onClick={() => {
                                setActiveCategory(section.category);
                                setActiveItem(item);
                                setMobileMenuOpen(false);
                              }}
                              className={`w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition-all ${
                                isSelected
                                  ? 'bg-gold/15 text-gold border border-gold/30 font-bold'
                                  : 'text-white/60 hover:text-white hover:bg-white/5'
                              }`}
                            >
                              {item}
                            </button>
                          </li>
                        );
                      })}
                    </ul>
                  </div>
                );
              })
            ) : (
              <div className="text-center py-8 text-white/40 text-xs font-medium">
                No matching topics found for "{searchQuery}"
              </div>
            )}
          </div>
        </div>

        <div className="p-4 sm:p-6 border-t border-white/10 mt-auto bg-[#050505]">
          <Link href="/" className="flex items-center gap-2 text-sm text-white/50 hover:text-white transition-colors">
            <ArrowLeft size={16} />
            Back to ZPAY Home
          </Link>
        </div>
      </aside>

      {/* Main Content Area - Mobile & Low End Device Optimized */}
      <main className="flex-1 bg-black min-h-screen overflow-x-hidden">
        <div className="max-w-4xl mx-auto px-4 sm:px-8 md:px-12 lg:px-16 py-8 sm:py-12 md:py-16">
          
          {/* Breadcrumbs */}
          <div className="flex flex-wrap items-center gap-2 text-xs text-white/40 mb-6 sm:mb-8 font-medium">
            <Link href="/" className="hover:text-white transition-colors">Docs</Link>
            <ChevronRight size={14} />
            <span>{currentDoc.category}</span>
            <ChevronRight size={14} />
            <span className="text-gold font-semibold">{currentDoc.title}</span>
          </div>

          {/* Article Header */}
          <div className="mb-8 sm:mb-10 border-b border-white/10 pb-6 sm:pb-8">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight mb-4 text-white">{currentDoc.title}</h1>
            <p className="text-white/60 text-base sm:text-lg leading-relaxed font-medium">
              {currentDoc.summary}
            </p>
          </div>

          {/* Code Snippet */}
          {currentDoc.codeSnippet && (
            <div className="mb-10 sm:mb-12 rounded-2xl border border-white/10 bg-[#0c0c0c] overflow-hidden shadow-2xl">
              <div className="flex items-center justify-between px-4 sm:px-5 py-3 border-b border-white/10 bg-white/[0.03]">
                <div className="flex items-center gap-2">
                  <Code size={14} className="text-gold" />
                  <span className="text-xs font-mono text-white/70">{currentDoc.codeSnippet.filename}</span>
                </div>
                <button 
                  onClick={() => copyCode(currentDoc.codeSnippet!.code)}
                  className="flex items-center gap-1.5 text-xs text-white/60 hover:text-white transition-colors py-1 px-2.5 rounded bg-white/5 border border-white/10"
                >
                  {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
              <div className="p-4 sm:p-6 overflow-x-auto">
                <pre className="text-xs sm:text-sm font-mono text-white/90 leading-relaxed">
                  <code>{currentDoc.codeSnippet.code}</code>
                </pre>
              </div>
            </div>
          )}

          {/* Article Sections */}
          <div className="space-y-8 sm:space-y-10">
            {currentDoc.sections.map((sec, idx) => (
              <section key={idx} className="space-y-3">
                <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-white flex items-center gap-2">
                  {sec.heading}
                </h2>
                <p className="text-white/60 text-sm sm:text-base leading-relaxed font-medium">
                  {sec.content}
                </p>
              </section>
            ))}
          </div>

          {/* Footer Navigation */}
          <div className="mt-16 sm:mt-20 pt-6 sm:pt-8 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4">
            <span className="text-xs text-white/40 font-mono">ZPAY Protocol Documentation v1.4</span>
            <Link 
              href="/support"
              className="text-xs text-gold hover:underline font-bold flex items-center gap-1"
            >
              Need help? Contact Developer Support <ChevronRight size={14} />
            </Link>
          </div>

        </div>
      </main>
    </div>
  );
}
